version: '3.5'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}

  app:
    container_name: app
    build:
      context: src/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    links:
      - mongo

  memory_check:
    container_name: memory_check
    build:
      context: memory_check/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
