version: '3.5'
services:
  mongo_1:
    container_name: mongo_1
    image: mongo:7.0.4
    restart: always
#    ports:
#      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    expose:
      - ${MONGO_DB_PORT}
    volumes:
      - 'mongo_volume:/data/db'

  flask_mongo_app:
    depends_on:
      - mongo_1
    build:
      context: src/.
      dockerfile: Dockerfile
    container_name: flask_mongo_app
#    ports:
#      - ${FLASK_PORT}:${FLASK_PORT}
    expose:
      - ${FLASK_PORT}
    restart: always
    env_file:
      - .env
#      Источник: https://advicemama.ru/dostup-k-konteineru-servera-docker-flask-nevozmozen-cerez-xost
#      - ${FLASK_PORT}:${FLASK_PORT}

  memory_check:
    container_name: memory_check
    build:
      context: memory_check/.
      dockerfile: Dockerfile
    restart: always

volumes:
  mongo_volume:

networks:
  default:
      name: nginx_proxy
      external: true