version: '3.5'
services:
  mongo_1:
    container_name: mongo_1
    image: mongo:7.0.4
    restart: always
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
#    expose:
#      - ${MONGO_DB_PORT}
    env_file:
      - .env
    volumes:
      - 'mongo_db:/data/db'
      - 'mongo_conf:/data/configdb'

  flask_mongo_app:
    depends_on:
      - mongo_1
    build:
      context: src/.
      dockerfile: Dockerfile
    container_name: flask_mongo_app
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
#    expose:
#      - ${FLASK_PORT}
    restart: always
    env_file:
      - .env
#      Источник: https://advicemama.ru/dostup-k-konteineru-servera-docker-flask-nevozmozen-cerez-xost

  memory_check:
    container_name: memory_check
    build:
      context: memory_check/.
      dockerfile: Dockerfile
    restart: always

volumes:
  mongo_db:
  mongo_conf:

networks:
  default:
      name: nginx_proxy
      external: true