version: '3.5'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
#    networks:
#      - my_network

  app:
    container_name: app
    build:
      context: src/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo
#    networks:
#      - my_network

  memory_check:
    container_name: memory_check
    build:
      context: memory_check/.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
#    networks:
#      - my_network


networks:
  default:
#    external: true
    name: my_network
